### ISSUE TITLE
There is still no .exe file (screenshots included)

### ISSUE THREAD

**Issue by gvivster** [Switch-9867/UnitypackgeExtractor#3]
Am I missing something?

![UnitypackgeExtractor Screenshot 2023-03-03 121624](https://user-images.githubusercontent.com/63889272/222797124-050caf57-53dc-4fa7-9bc1-b1423f3a5db7.png)
![UnitypackgeExtractor Screenshot 2023-03-03 121649](https://user-images.githubusercontent.com/63889272/222797150-adc13d03-bebf-4292-8757-a2aae0f01fb3.png)

I downloaded it from the link you mentioned in [the previous issue](https://github.com/Switch-9867/UnitypackgeExtractor/issues/2).
![UnitypackgeExtractor Screenshot 2023-03-03 122019](https://user-images.githubusercontent.com/63889272/222797666-940c9c97-23ff-4d6b-b457-fb61413973e1.png)

**Comment by Switch-9867** [comment]
Yes, you are downloading the source code. Please try cliking "UnitypackageExtractor_100.zip"

**Comment by gvivster** [comment]
Ahh, thank you. I didn't realize that was a download link too.
